services:
  postgress:
    container_name: postgres-flashcards
    image: postgres
    environment:
      POSTGRES_USER: aniad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashcard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-boot-network


volumes:
  postgres:

networks:
  spring-boot-network:
    driver: bridge